jobs:
- job: macOS
  pool:
    vmImage: xcode9-macos10.13
  steps:
    - bash: |
        sudo xcode-select --switch /Applications/Xcode_10.app/Contents/Developer
        brew update-reset
        ln -s "$PWD" "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle"
        # TODO: RuboCop needs fixed in
        # https://github.com/Homebrew/homebrew-bundle/pull/384
        # brew style homebrew/bundle
        bundle install
        bundle exec rake
      displayName: Tests
